/// Flutter icons CustomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

/// A utility class containing the icon data for some custom icons.
class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String/*?*/ _kFontPkg = null;

  static const IconData headphones = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy = IconData(0xf091, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullhorn = IconData(0xf0a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase = IconData(0xf0b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flask = IconData(0xf0c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xf0e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_empty = IconData(0xf0e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stethoscope = IconData(0xf0f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee = IconData(0xf0f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building = IconData(0xf0f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code = IconData(0xf121, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube_play = IconData(0xf16a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xf16d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank = IconData(0xf19c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tree = IconData(0xf1bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinterest = IconData(0xf231, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wikipedia_w = IconData(0xf266, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_squared = IconData(0xf308, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData table_tennis = IconData(0xf45d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drafting_compass = IconData(0xf568, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swimmer = IconData(0xf5c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData umbrella_beach = IconData(0xf5ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
